### ISSUE TITLE
No syntax highlighting in code blocks

### ISSUE THREAD

**Issue by mc-marcocheng** [dracula/mkdocs#13]
![image](https://user-images.githubusercontent.com/57459045/230770659-1f7eefe8-2e81-48ba-9bf4-bf1906c487b8.png)

**Comment by FernandoCelmer** [comment]
@mc-marcocheng, Nice that you noticed the issue regarding no syntax highlighting in blocks of code. I'll validate and see if it can improve.

If you want, feel free to collaborate. :D

**Comment by FernandoCelmer** [comment]
Hi @Ymil, about this implementation, check if I'm ok, this coding, I implemented a `default` mode for the `highlight` and also a new configuration to include the `file.css` for importing another `highlight` style.

![image](https://github.com/dracula/mkdocs/assets/6262214/92ffd478-e82c-4db5-a820-02f0d182b0af)

The configuration for a customizable style is `highlight_css`:

```yml
theme:
  name: dracula
  logo: assets/img/dracula.png
  favicon: assets/img/favicon.ico
  highlight_css: atom-one-dark.min.css
```

![image](https://github.com/dracula/mkdocs/assets/6262214/362807a8-e87b-4858-a8c4-a9915f6016f6)

To test, just use this command: 

- `pip install -i https://test.pypi.org/simple/ mkdocs-dracula-theme==1.0.7.dev3`
    - [mkdocs-dracula-theme 1.0.7.dev3 ](https://test.pypi.org/project/mkdocs-dracula-theme/1.0.7.dev3/)
